### ISSUE TITLE
Tracklist UI unresponsive without internet

### ISSUE THREAD

**Issue by kenherbert** [orontee/argos#181]
Running on Raspian (Bookworm).

When I have no internet the tracklist page UI becomes unusable - the buttons and track list do not respond to interaction at all.

If I start Argos without internet this means I can't play anything already queued (even from a local source).

If I start Argos with internet then lose connection (turn off the hotspot, move out of range, etc.) the local music continues to play, the album artwork, artist name, track title, and track length continue to update, but I am no longer able to play/pause, skip back/forward, change volume, scroll the queue, and the current play time defaults back to --:--.

Titlebar continues to work, so I can switch to other pages and back to the tracklist page, and the library page seems to function properly (but have't tested much) - it is only the tracklist page that is affected.

**Comment by orontee** [comment]
Thank you @kenherbert for your interest in Argos. 

Current implementation is as follow: When the network is not available, any widget displaying data coming from Mopidy server is supposed to become insensitive, no interaction is possible; If the widget has dynamic content (like the play duration you mention), a specific value is displayed, meaning the right value is not known anymore. The rationale is forbid interaction with widget supposed to act on Mopidy server and don't display out-of-date data.

As far as I understand, your description matches the expected behavior.

But here "network being unavailable"  means  a default route for IPV4 or IPV6 is available. I understand that it's not always an appropriate criteria: For example if Argos and Mopidy run on the same host. @kenherbert  Is it your setup?

A nice improvement could be to check whether the server is reachable on network availability changes using https://docs.gtk.org/gio/method.NetworkMonitor.can_reach.html.

**Comment by orontee** [comment]
@kenherbert Can you check current head? It contains a fixed that improves the situation when both Argos and Mopidy run on the same host.

I created #182 to improve the user experience when editing Mopidy base URL.

**Comment by kenherbert** [comment]
> But here "network being unavailable" means a default route for IPV4 or IPV6 is available. I understand that it's not always an appropriate criteria: For example if Argos and Mopidy run on the same host. @kenherbert Is it your setup?

Yes, I have Mopidy and Argos both running on the same Raspberry Pi.

Thanks for the quick update, I will try to test it over the weekend.
